version: '3'

services:
  configserver:
    image: jamesvrooney/config-server:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    networks:
      - backend

  licensingservice:
    image: jamesvrooney/licensing:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8082"
      CONFIGSERVER_PORT: "8082"
      DATABASESERVER_PORT: "5432"
    depends_on:
      - database
      - configserver
    networks:
      - backend

  database:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: jamesvrooney
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  postgres:
  pgadmin: